config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end


  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

get 'login/index'
get 'jobbank/joblist'
get 'form/index'
get 'managa_user/list'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

def is_admin?
 self.admin == 1
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_admin_user!
  authenticate_user!
    unless current_user.admin?
    flash[:alert] = "This area is restricted to administrators only."
    redirect_to root_path
  end
 end

def current_admin_user
  return nil if user_signed_in? && !current_user.admin?
  current_user
end

def after_sign_in_path_for(resource)
if current_user.admin?
	authenticated_root_path
else
    login_index_path
end
end
  before_filter :authenticate_user!
  before_filter :set_cache_buster
  
  def set_cache_buster
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
 
  def authenticate_admin_user!
     authenticate_user!
      unless current_user.admin?
      flash[:alert] = "This area is restricted to administrators only."
      redirect_to root_path
     end
   end

 def current_admin_user
    return nil if user_signed_in? && !current_user.admin?
    current_user
 end

 def after_sign_in_path_for(resource)
    if current_user.admin?
    	 authenticated_root_path
    else
        login_index_path
    end
 end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  layout 'dashboard'
  def index
  end
end

app/controllers/form_controller.rb
class FormController < ApplicationController
  def index
  end
end

app/controllers/jobbank_controller.rb
class JobbankController < ApplicationController
  def joblist
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	before_filter :authenticate_user!
  def index
  end
end

app/controllers/managa_user_controller.rb
class ManagaUserController < ApplicationController
  def list
  end
end

app/controllers/users/confirmations_controller.rb
class users::confirmationsController < Devise::confirmationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
class users::passwordsController < Devise::passwordsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/registrations_controller.rb
class users::registrationsController < Devise::registrationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/sessions_controller.rb
class users::sessionsController < Devise::sessionsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/unlocks_controller.rb
class users::unlocksController < Devise::unlocksController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/jobbank_helper.rb
module JobbankHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/managa_user_helper.rb
module ManagaUserHelper
end

app/views/dashboard/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jfast</title>
      <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	

app/views/dashboard/index.html.erb
   <div id="page-wrapper">
      <div class="row">
        <div class="col-lg-12">
          <h5 class="page-header">Dashboard  Logged in as <strong><%= current_user.email %></strong></h5>
         </div>
        </div>

            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-comments fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">26</div>
                                    <div>New Comments!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">12</div>
                                    <div>New Tasks!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-shopping-cart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">124</div>
                                    <div>New Orders!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-support fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">13</div>
                                    <div>Support Tickets!</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>

app/views/form/index.html.erb
<%= render 'layouts/sidebar' %>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h5 class="page-header">Form <strong><%= current_user.email %></strong></h5>
        </div>
    </div>
</div>

app/views/jobbank/joblist.html.erb
<%= render 'layouts/sidebar' %>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h5 class="page-header">JOBLIST <strong><%= current_user.email %></strong></h5>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jfast</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	   

app/views/layouts/_sidebar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">JFAST V1.0</a>
    </div>
    <!-- /.navbar-header -->

      <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
        <% if user_signed_in? %>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
        <% end %>
        </li>
    </ul>

      <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
        <% if user_signed_in? %>
        <%= link_to '<i class="fa fa-sign-out fa-fw"></i>logout'.html_safe, destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% end %>
        </li>
    </ul>

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                    </div>
                    <!-- /input-group -->
                </li>
                <li><%= link_to '<i class="fa fa-dashboard fa-fw"></i> Dashboard'.html_safe,  authenticated_root_path %></li>
                <li><a href=""><i class="fa fa-bar-chart-o fa-fw"></i>&nbsp;Job Bank List<span class="fa arrow"></span></a>
                  <ul class="nav nav-second-level">
                        <li><%= link_to 'List',  jobbank_joblist_path %></li>
                        <li><a href="morris.html">Morris.js Charts</a></li>
                  </ul>
                </li>
                
                <li><%= link_to 'Form',  form_index_path %></li>
                
                   <li><a href="#"><i class="fa fa-wrench fa-fw"></i>Manage user<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                             <li><%= link_to 'user list',  managa_user_list_path %></li>
                        </li>
                    </ul>
                </li>
   
                <li><a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="blank.html">Blank Page</a></li>
                        <li> <a href="login.html">Login Page</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<%= render "layouts/header" %>
  <% if notice %><p class="alert alert-success"><%= notice %></p><% end %>
  <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
  <%= yield %>
<%= render "layouts/footer"%>

app/views/layouts/dasboard.html.erb
<%= render "layouts/header" %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>

 <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
 <% end %>

<%= yield %>
<%= render "layouts/footer"%>

app/views/layouts/dashboard.html.erb
<%= render "layouts/header" %>
<%= render 'layouts/sidebar'%>

  <% if notice %><p class="alert alert-success"><%= notice %></p><% end %>
  <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
  <%= yield %>
<%= render "layouts/footer"%>

app/views/login/index.html.erb
<div class="login-card">
  <form>
    <input type="text" name="user">
    <input type="password" name="pass" id = "username" >
    <input type="submit" name="login" id = "password" class="login login-submit" value="login">
  </form>

 </div>

app/views/managa_user/list.html.erb
<%= render 'layouts/sidebar' %>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h5 class="page-header">manage User <strong><%= current_user.email %></strong></h5>
        </div>
    </div>
</div>